title: Astartup
subtitle: The Astartup Live-stream and IMUL Web-App.
description: >- # this means to ignore newlines until "baseurl:"
  I am You Language (IMUL) is the language of productivity invented for the Astartup to perform Issue-driven Development (IDD). The Astartup is a productivity, learning, and creativity revolution and you just landed at ground zero!

url: "https://astartup.net" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Estuary
      url: /estuary
    - text: Discover
      url: /discover
    - text: Jobs
      url : /jobs
    - text: Resources
      url : /resources
    

# Edit these details 

author_logo: astartup.logo.png
author: Astartup™
author_bio: Astartup™ is powered by I am You Language™ (IMUL™), creativity, and the power of the pen!  
author_email: "kabuki@astartup.net"
author_location: Eugene, Oregon USA
author_website_url: "https://kabukistarship.com"

author_project_details:
              - project_thumbnail: astartup.cookbook.png
                project_title: Astartup Cookbook
                project_description: A open-source book on how to invent, launch, and run a modern startup with I am You Language (IMUL).
                project_url: https://github.com/a-startup/astartup.cookbook
                visibility: true
              - project_thumbnail: kabuki.press.cookbook.png
                project_title: KabukiPress Cookbook
                project_description: A Platform to easily find and read programming books
                project_url: https://github.com/kabuki-starship/kabuk.press.cookbook
                visibility: true
              - project_thumbnail: greentech.cookbook.png
                project_title: Greentech Cookbook
                project_description: A Platform to easily find and read programming books
                project_url: https://github.com/oregon-cooler/oregoncooler.cookbook
                visibility: true
              - project_thumbnail: script2.png
                project_title: Script2
                project_description: A Modern Embedded-C++ unit test and IoT application nanoframework and the SCRIPT Specification.
                project_url: https://github.com/kabuki-starship/script2
                visibility: true
              - project_thumbnail: kabuki.toolkit.png
                project_title: Kabuki Toolkit
                project_description: A Modern Embedded-C++, Script2, and IMUL toolkit for making intelligent connected software and art.
                project_url: https://github.com/kabuki-starship/kabuki.toolkit
                visibility: true
              - project_thumbnail: kabuki.toolkit.tek.png
                project_title: Kabuki Tek Toolkit
                project_description: A Modern Embedded-C++ and Script2 firmware toolkit.
                project_url: https://github.com/kabuki-starship/kabuki.toolkit.tek
                visibility:  true
              - project_thumbnail: kabuki.press.png
                project_title: KabukiPress
                project_description: A Modern Embedded-C++, Script2, and IMUL web and document framework and server.
                project_url: https://github.com/kabuki-starship/kabuki.press
                visibility:  true

# social links
twitter_username: astarstartup
github_username:  a-startup
#facebook_username: astartup
#linkedin_username: astartup
#behance_username: astartup
#instagram_username: engineer_cale
#medium_username: astartup
#telegram_username: astartup
#dribbble_username: astartup
#flickr_username: astartup

#for comments using disqus
disqus_shortname: astartup  

# wakatime username (coding activity)
#wakatime_username: astartup

# formspree (contact form)
formspree_email: kabuki@astartup.net

# syntax highlighter
markdown: redcarpet
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: false
show_author_education_details: false
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: streams # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/estuary/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - startups
 - organizations
 - projects

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/